# Generated by Django 5.1.4 on 2024-12-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
