# Generated by Django 5.1.4 on 2025-01-08 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_iteracao_curtida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curtida',
            old_name='criado_em',
            new_name='curtida_criada',
        ),
    ]
