# Generated by Django 5.1.4 on 2025-01-09 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_rename_criado_em_curtida_curtida_criada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iteracao',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='iteracao',
            name='profile_id',
        ),
        migrations.DeleteModel(
            name='Curtida',
        ),
        migrations.DeleteModel(
            name='Iteracao',
        ),
    ]
