# Generated by Django 5.1.4 on 2025-01-09 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_iteracao_curtida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iteracao',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='iteracao',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Curtida',
        ),
        migrations.DeleteModel(
            name='Iteracao',
        ),
    ]
