# Generated by Django 5.1.4 on 2025-01-09 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_profile_profile_connections'),
        ('feed', '0007_remove_iteracao_post_id_remove_iteracao_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iteracao',
            fields=[
                ('iteracao_id', models.AutoField(primary_key=True, serialize=False)),
                ('iteracao_comentario', models.TextField()),
                ('iteracao_criada', models.DateTimeField(auto_now_add=True)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iteracao', to='feed.post')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iteracao', to='cadastro.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Curtida',
            fields=[
                ('cutida_id', models.AutoField(primary_key=True, serialize=False)),
                ('curtida_criada', models.DateTimeField(auto_now_add=True)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas', to='feed.post')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas', to='cadastro.profile')),
            ],
            options={
                'unique_together': {('post_id', 'profile_id')},
            },
        ),
    ]
